### ISSUE TITLE
kod wyjścia

### ISSUE THREAD

**Issue by setaur** [3ed/napi-bash#4]
W tym zacnym programie shellowym przydałyby się kody wyjścia, tak żeby można było łatwo zaimplementować jego użycie w kolejnych skryptach. Chociażby tyle, żeby kody wyjścia w przypadku nie odnalezienia napisu (wszystkich napisów) różnił się od domyślnego 0 w przypadku pełnego sukcesu.
Pozdrawiam!

**Comment by 3ed** [comment]
W wersji master git kod wyjścia pownien mieć 2.
