### ISSUE TITLE
problem z instalacją

### ISSUE THREAD

**Issue by setaur** [3ed/napi-bash#5]
Znowu ja :)
Mam problem z instalacją z gita.
Po ściągnięciu i zgodnie z tym co pisze w INSTALL daję

`# make install PREFIX=/usr`
`make: *** Brak reguł do wykonania obiektu 'install'. Stop.`

Odpalam to oczywiście z roota w katalogu ze ściągniętym napi-bash.

**Comment by 3ed** [comment]
Sorry, wiki jest dla wersji 1.0. Spróbuj:
 ./autogen.sh
 ./configure --prefix=/usr
 make install

**Comment by setaur** [comment]
$ ./autogen.sh 
Running autogen.sh...
  Running aclocal...
./autogen.sh: linia 5: aclocal: nie znaleziono polecenia
  Running autoconf...
./autogen.sh: linia 7: autoconf: nie znaleziono polecenia
  Running automake...
./autogen.sh: linia 9: automake: nie znaleziono polecenia

**Comment by 3ed** [comment]
`./autogen.sh` wygeneruje plik `./configure`, żeby to zrobić potrzebne są pakiety: `automake` i `autoconf`. `./configure` wygeneruje plik `Makefile`, który będzie wczytany przez polecenie `make`. Normalnie urzytkownik nie musi się tym przejmować, dostaje gotowy pakiet lub plik budujący z informacją o zależnościach. Odnośnie tego mechanizmu, ręczne pisanie pliku `Makefile` zaczęło być męczące, plik stawał się długi i skomplikowany (szczególnie przy systemie wtyczek), nie było sprawdzania zależności i programu konfiguracyjnego... Narzędzia wymienione wyżej są standardowymi narzędziami kompilatora gcc (języki c i c++ oraz inne). Pliki `lib/` (wtyczki) również muszą być zainstalowane. Tak, plik INSTALL trzeba zakualizować, dodam do todo.

Odnośnie notyfikacji, to nie mam pojęcia, potestuje to, u mnie działa. Jak już program się zainstaluje to fajnie by było zobaczyć tryb debug z tej najnowszej wersji...

Pozdrawiam.

**Comment by setaur** [comment]
po zainstalowaniu automake i autoconf gra i buczy :)
