### ISSUE TITLE
Zmiana kodowania z BOM

### ISSUE THREAD

**Issue by dracorp** [3ed/napi-bash#6]
Witam
Aktualnie napi-bash nie zmienia kodowania z UTF-8 na inne jeśli jest użyty znacznik kolejności bajtów, [BOM](https://pl.wikipedia.org/wiki/BOM_%28informatyka%29). Dokładnie to iconv nie radzi sobie z tym:
```
iconv plik -f UTF-8 -t WINDOWS-1250
iconv: błędna sekwencja wejściowa na pozycji 0
```
Poleceniem grep możesz zweryfikować czy BOM istnieje:
```
grep $'\xEF\xBB\xBF' -q plik
```
a poleceniem sed usunąć go (lub od razu to zrobić):
```
sed '1s/^\xEF\xBB\xBF//' -i plik
```
ps. Polecenie enconv (z pakietu enca) w locie zamienia kodowanie ale też sobie nie radzi z BOM.

**Comment by 3ed** [comment]
Zaktualizowałem kod w git. Jestem całkiem pewny, że powinno działać. :)
