### ISSUE TITLE
Brak wsparcia dla UTF-16

### ISSUE THREAD

**Issue by dracorp** [3ed/napi-bash#7]
Aktualnie w programie jest wsparcie tylko dla UTF8. Jeśli plik jest w kodowaniu UTF-16 to i tak jest traktowany jako UTF-8:
```
        *utf*) from="UTF8";;
```
Polecenie file mówi że plik jest:
```
Little-endian UTF-16 Unicode text, with CRLF line terminators
```

Usunięcie BOMa dla utf-16le nieszczególnie pomogło iconvowi.

Pozdrawiam Piotr

**Comment by 3ed** [comment]
Dodałem UTF16 i UTF32. Użyłem opcji iconv „TRANSLIT”, nie wiem kiedy została wprowadzona, zazwyczaj staram się używać rzeczy kompatybilnych z dystrybucjami „LTS”… Przetestowałem to na szybko i u mnie działa. Przydałaby się druga opinia. :)

BTW: TRANSLIT zastąpił awka (issue/6)…

**Comment by dracorp** [comment]
Potwierdzam, działa. O tej opcji też nie wiedziałem.
